server:
  port: 20001
  servlet:
    context-path: /api/v1
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8066/changgou_admin_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
sc:
  worker:
    workerId: 1
    datacenterId: 1